- name: install openjdk-8-jre for redhat
  yum: name=openjdk-8-jre state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install openjdk-8-jre for ubuntu
  apt: name=openjdk-8-jre state=present
  when: ansible_distribution == 'Ubuntu'

- name: install openjdk-8-jdk for redhat
  yum: name=openjdk-8-jdk state=present disable_gpg_check=yes
  when: ansible_os_family == 'RedHat'

- name: install openjdk-8-jdk for ubuntu
  apt: name=openjdk-8-jdk state=present
  when: ansible_distribution == 'Ubuntu'

- name: tar file
  shell: mkdir -p /tmp/scimarkJava

- name: copy file
  copy: src=scimark2lib.tar.gz dest=/tmp/scimark2lib.tar.gz mode=0777

- name: tar scimark2lib.tar.gz
  shell: "cd /tmp && tar -xvf scimark2lib.tar.gz"